### ISSUE TITLE
Issue with metadata: cpu_time

### ISSUE THREAD

**Issue by huangeyou007** [IBM/Project_CodeNet#27]
Hi!
I have some confusion about cpu_time. Why is there zero value for cpu_time?
![image](https://user-images.githubusercontent.com/19648077/123604209-389eef00-d82d-11eb-99cd-9105e22784c1.png)

**Comment by geert56** [comment]
You have to realize that the metadata provided comes directly from the online judging sites. If AIZU records 0 for cpu_time then it show up as such in our metadata CSV file. Mind also that the resolution of the measurement is milliseconds; a lot of programs run very fast, maybe even in less than 1 millisecond. That measurement might then be rounded down to 0 (since the column lists integer numbers). We did NOT run all Accepted submissions ourselves and recorded their cpu_time. That might be a good exercise to obtain more precise numbers. Note that some of the rejected submissions have negative cpu_time. We have no explanation for that.
