### ISSUE TITLE
garbled codes in some code files

### ISSUE THREAD

**Issue by Sunning2118** [IBM/Project_CodeNet#56]
There are garbled codes in some code files, which may affect semantic analysis, such as: s969976977.java
![image](https://github.com/IBM/Project_CodeNet/assets/73994854/74faa202-d5fc-4362-93e1-42df4adfa4cf)

**Comment by geert56** [comment]
Your assessment of this being garbled code is probably based on the funny comments with all the question marks.
But really, this is a correct Java problem that is part of the accepted answers to problem p02407.
(By the way, instead of using a screen capture and inserting an image here, it is better to use a literal code block.)

**Comment by Sunning2118** [comment]
> Your assessment of this being garbled code is probably based on the funny comments with all the question marks. But really, this is a correct Java program that is part of the accepted answers to problem p02407. (By the way, instead of using a screen capture and inserting an image here, it is better to use a literal code block.)

Thank you！
